### ISSUE TITLE
config location issue when using official Ghost Docker image

### ISSUE THREAD

**Issue by rija** [bennetimo/ghost-backup#3]
Hi

I like this project, I find it useful and well designed. I wanted to use it with the Ghost's official Alpine-based  [Docker image](https://hub.docker.com/_/ghost/) but I ran into the issue below while testing the interactive restore.

```
Select DB or Ghost archive file to restore, or 'q' to quit
1) /backups/backup-db_20180731-1049.gz
2) /backups/backup-ghost_20180731-1049.tar.gz
Restore #: 1
Tue Jul 31 10:54:41 UTC 2018: restoring data from sqlite dump file: /backups/backup-db_20180731-1049.gz
Tue Jul 31 10:54:42 UTC 2018: ...restored ghost DB archive /backups/backup-db_20180731-1049.gz
Tue Jul 31 10:54:42 UTC 2018: restore complete
Restore #: 2
Tue Jul 31 10:54:47 UTC 2018: removing ghost files in /var/lib/ghost/content
rm: cannot remove '/var/lib/ghost/content/config.js': No such file or directory
```

It turns out that ghost-backup and Ghost for Docker have different understanding about location and name of config files:

* Ghost installs the config files in ``/var/lib/ghost/`` as **config.production.json** while the rest of the files are installed under ``/var/lib/ghost/content``
* ghost-backup expects all files and **config.js** to be under $GHOST_LOCATION

I guess Ghost has changed a lot over the last couple of years.
I'll try to come up with a fix and contribute a PR.

**Comment by bennetimo** [comment]
Fixed in the latest version. Thanks for your contribution :)
