### ISSUE TITLE
Problems with Urls after restoring from backup

### ISSUE THREAD

**Issue by ayedo** [bennetimo/ghost-backup#5]
Hi Bennetimo,

first of all, thanks for your great work on this docker image. I have enjoyed using it so far :)

Just as a test, I'm trying to restore a ghost 2.25.4 backup using ghost-backup. Most things worked out of the box, but somehow the urls to the images are off. 

Do you maybe have experience with such problems? 

I've noticed that you have labeled the image 1.25 - is the ghost version I am using (2.25.4) maybe not supported by ghost-backup?

Thanks & Cheers,
Alon

**Comment by bennetimo** [comment]
Hi Alon, glad you're enjoying it :)  I've been using Ghost 2.2 so it's possible there are some changes between there and 2.25. Having said that, I've just tried restoring into a 2.25 install and the image paths worked okay. 

Can you give a bit more context/some examples of the mistmatched urls you're seeing? And are you restoring via json or db?

**Comment by ayedo** [comment]
Ah, it was me all along :)

My production blog's URL is set to `http://example.com/blog`, and when I tried to locally restore the backup I forgot to start the container with `url=http://localhost:3001/blog`. Now all is restored correctly.

Sorry for the confusion & thanks for your help!
